### ISSUE TITLE
Fails to suspend

### ISSUE THREAD

**Issue by lll2yu** [guns/go-luks-suspend#10]
Instead of suspending the system powers off.
I'm using `luks2`.

Here's the output of `/usr/lib/go-luks-suspend/go-luks-suspend -debug`

> 2018/07/12 14:47:13 disabling ISIG in TTY
2018/07/12 14:47:13 checking suspend program in initramfs
2018/07/12 14:47:13 gathering cryptdevices
2018/07/12 14:47:13 Name:"" IsRootDevice:false
2018/07/12 14:47:13 running pre-suspend scripts
2018/07/12 14:47:13 gathering filesystems with write barriers
2018/07/12 14:47:13 preparing initramfs chroot
2018/07/12 14:47:13 stopping selected system services
2018/07/12 14:47:13 exec: /usr/bin/systemctl --quiet is-active syslog.socket
2018/07/12 14:47:13 exec: /usr/bin/systemctl --quiet is-active systemd-journald.socket
2018/07/12 14:47:13 exec: /usr/bin/systemctl --quiet is-active systemd-journald-dev-log.socket
2018/07/12 14:47:13 exec: /usr/bin/systemctl --quiet is-active systemd-journald-audit.socket
2018/07/12 14:47:13 exec: /usr/bin/systemctl --quiet is-active systemd-journald.service
2018/07/12 14:47:13 exec: /usr/bin/systemctl --quiet is-active systemd-udevd-control.socket
2018/07/12 14:47:13 exec: /usr/bin/systemctl --quiet is-active systemd-udevd-kernel.socket
2018/07/12 14:47:13 exec: /usr/bin/systemctl --quiet is-active systemd-udevd.service
2018/07/12 14:47:13 exec: /usr/bin/systemctl stop systemd-journald.socket systemd-journald-dev-log.socket systemd-journald.service systemd-udevd-control.socket systemd-udevd-kernel.socket systemd-udevd.service
2018/07/12 14:47:13 flushing pending writes
2018/07/12 14:47:13 disabling write barriers on filesystems to avoid IO hangs
2018/07/12 14:47:13 calling suspend in initramfs chroot
2018/07/12 09:17:13 loading cryptdevices
2018/07/12 09:17:13 suspending cryptdevices
2018/07/12 09:17:13 exec: /usr/bin/cryptsetup luksSuspend 
2018/07/12 09:17:13 exit status 4
2018/07/12 09:17:13 ===========================
2018/07/12 09:17:13         DEBUG SHELL        
2018/07/12 09:17:13 ===========================
[/ #] 

`journalctl`
> Jul 11 19:09:13 naavi systemd-logind[1141]: Lid closed.
Jul 11 19:09:13 naavi systemd-logind[1141]: Suspending...
Jul 11 19:09:13 naavi NetworkManager[1140]: <info>  [1531316353.6693] manager: sleep: sleep requested (sleeping: no  enabled: yes)
Jul 11 19:09:13 naavi NetworkManager[1140]: <info>  [1531316353.6694] device (enp7s0): state change: unavailable -> unmanaged (reason>
Jul 11 19:09:13 naavi root[20649]: LID closed
Jul 11 19:09:14 naavi NetworkManager[1140]: <info>  [1531316354.0019] manager: NetworkManager state is now ASLEEP
Jul 11 19:09:14 naavi NetworkManager[1140]: <info>  [1531316354.0027] device (wlp6s0): state change: activated -> deactivating (reaso>
Jul 11 19:09:14 naavi kernel: wlp6s0: deauthenticating from 70:62:b8:fd:cb:d1 by local choice (Reason: 3=DEAUTH_LEAVING)
Jul 11 19:09:14 naavi dbus-daemon[1139]: [system] Activating via systemd: service name='org.freedesktop.nm_dispatcher' unit='dbus-org>
Jul 11 19:09:14 naavi NetworkManager[1140]: <info>  [1531316354.0086] device (wlp6s0): state change: deactivating -> disconnected (re>
Jul 11 19:09:14 naavi NetworkManager[1140]: <info>  [1531316354.0090] dhcp4 (wlp6s0): canceled DHCP transaction
Jul 11 19:09:14 naavi NetworkManager[1140]: <info>  [1531316354.0090] dhcp4 (wlp6s0): state changed bound -> done
Jul 11 19:09:14 naavi systemd[1]: Starting Network Manager Script Dispatcher Service...
Jul 11 19:09:14 naavi wpa_supplicant[1216]: wlp6s0: CTRL-EVENT-DISCONNECTED bssid=70:62:b8:fd:cb:d1 reason=3 locally_generated=1
Jul 11 19:09:14 naavi NetworkManager[1140]: <info>  [1531316354.0274] device (wlp6s0): set-hw-addr: set MAC address to 76:25:C6:E7:0E>
Jul 11 19:09:14 naavi kernel: IPv6: ADDRCONF(NETDEV_UP): wlp6s0: link is not ready
Jul 11 19:09:14 naavi dbus-daemon[1139]: [system] Successfully activated service 'org.freedesktop.nm_dispatcher'
Jul 11 19:09:14 naavi systemd[1]: Started Network Manager Script Dispatcher Service.
Jul 11 19:09:14 naavi NetworkManager[1140]: <warn>  [1531316354.0321] sup-iface[0x559f4c49f170,wlp6s0]: connection disconnected (reas>
Jul 11 19:09:14 naavi NetworkManager[1140]: <info>  [1531316354.0322] device (wlp6s0): supplicant interface state: completed -> disco>
Jul 11 19:09:14 naavi nm-dispatcher[20650]: req:1 'connectivity-change': new request (0 scripts)
Jul 11 19:09:14 naavi NetworkManager[1140]: <info>  [1531316354.0336] device (wlp6s0): state change: disconnected -> unmanaged (reaso>
Jul 11 19:09:14 naavi nm-dispatcher[20650]: req:1 'connectivity-change': completed: no scripts
Jul 11 19:09:14 naavi NetworkManager[1140]: <info>  [1531316354.0347] device (wlp6s0): set-hw-addr: reset MAC address to 2C:6E:85:1F:>
Jul 11 19:09:14 naavi nm-dispatcher[20650]: req:2 'down' [wlp6s0]: new request (0 scripts)
Jul 11 19:09:14 naavi nm-dispatcher[20650]: req:2 'down' [wlp6s0]: completed: no scripts
Jul 11 19:09:14 naavi systemd[1]: Starting TLP suspend/resume...
Jul 11 19:09:14 naavi wpa_supplicant[1216]: nl80211: Failed to open /proc/sys/net/ipv4/conf/p2p-dev-wlp6s0/drop_unicast_in_l2_multica>
Jul 11 19:09:14 naavi wpa_supplicant[1216]: nl80211: Failed to set IPv4 unicast in multicast filter
Jul 11 19:09:14 naavi wpa_supplicant[1216]: nl80211: Failed to open /proc/sys/net/ipv4/conf/p2p-dev-wlp6s0/drop_unicast_in_l2_multica>
Jul 11 19:09:14 naavi wpa_supplicant[1216]: nl80211: Failed to set IPv4 unicast in multicast filter
Jul 11 19:09:14 naavi wpa_supplicant[1216]: nl80211: deinit ifname=p2p-dev-wlp6s0 disabled_11b_rates=0
Jul 11 19:09:14 naavi wpa_supplicant[1216]: nl80211: deinit ifname=wlp6s0 disabled_11b_rates=0
Jul 11 19:09:14 naavi systemd[1]: Started TLP suspend/resume.
Jul 11 19:09:14 naavi systemd[1]: Reached target Sleep.
Jul 11 19:09:14 naavi systemd[1]: Starting Suspend...
Jul 11 19:09:14 naavi systemd[1]: Stopped Flush Journal to Persistent Storage.
Jul 11 19:09:14 naavi systemd-journald[652]: Journal stopped
-- Reboot --

**Comment by dlight** [comment]
Is this resolved?

I'm using https://github.com/vianney/arch-luks-suspend currently without problems, with luks and lvm. Only problem is it's unmaintained, so I'm thinking to move to go-luks-suspend, but am wary to hit this bug. :cry:

**Comment by lll2yu** [comment]
@dilght I'm still facing it.

Though I'm using luks2, it may work nicely with your setup. You should give it a try.

**Comment by Maryse47** [comment]
@lll2yu  You need this for luks2 support https://github.com/guns/go-luks-suspend/commit/f735dda3b34ae7bf53290de4f6da25092cf9ef27 
@guns please add above to main branch.

**Comment by lll2yu** [comment]
Fixed using `luks2` branch.
Thanks @Maryse47
