### ISSUE TITLE
AUR package missing

### ISSUE THREAD

**Issue by benruijl** [guns/go-luks-suspend#2]
Your package looks great, but does not exist in the AUR (the link is dead).

If your package is uploaded, I suggest to flag this old one for deletion: https://aur.archlinux.org/packages/arch-luks-suspend-git/#

**Comment by guns** [comment]
Thanks! I actually just never got around to uploading to the AUR. I'll read the docs and do it tonight.

**Comment by guns** [comment]
Okay, I uploaded to https://aur.archlinux.org/packages/go-luks-suspend/

Thanks for the push!
