### ISSUE TITLE
mkinitcpio Hook 'suspend' cannot be found

### ISSUE THREAD

**Issue by tetov** [guns/go-luks-suspend#7]
README.md under [Installation](https://github.com/guns/go-luks-suspend#installation) 

> 2. Edit `/etc/mkinitcpio.conf` and make sure the following hooks are enabled:
> `udev`, `encrypt`, `shutdown`, and `suspend`

Should `suspend` be changed to `resume`?

[Here](https://wiki.archlinux.org/index.php/Mkinitcpio#Common_hooks) is a table of common hooks.

These are the available hooks on my Arch Linux Setup:
```
$ mkinitcpio -L
==> Available hooks
autodetect	dmraid		hostdata	mdadm_udev	pcmcia		sd-lvm2		strip		usr
base		encrypt		keyboard	memdisk		resume		sd-shutdown	systemd		virtio¹
block		filesystems	keymap		mmc¹		sata¹		sd-vconsole	udev
btrfs		fsck		lvm2		modconf		scsi¹		shutdown	usb¹
consolefont	fw¹		mdadm		pata¹		sd-encrypt	sleep		usbinput²

¹ This hook is deprecated in favor of 'block'
² This hook is deprecated in favor of 'keyboard'
```

**Comment by guns** [comment]
The `suspend` hook is present at `/usr/lib/initcpio/install/suspend` after installation. Did you install from the AUR?

**Comment by tetov** [comment]
I did step 2 before step 1 since I were already editing mkinitcpio.conf and I didn't think the suspend hook would be provided by the AUR package.

I have installed it now, and mkinitcpio -P worked with no errors and when I suspend I have to enter my passkey. So everything works. Sorry to be a bother!

**Comment by guns** [comment]
No problem! Thanks for reporting.
